# Generated by Django 6.0.3 on 2026-04-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_akoka',
            field=models.BooleanField(default=False),
        ),
    ]
