# Generated by Django 6.0.3 on 2026-04-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
