# Generated by Django 6.0.3 on 2026-03-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('partnership_type', models.CharField(choices=[('hotel', 'Hotel Partnership'), ('event', 'Event Collaboration'), ('agency', 'Travel Agency'), ('corporate', 'Corporate Travel')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
