# Generated by Django 6.0.3 on 2026-03-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('early', 'Early Bird'), ('regular', 'Regular'), ('vip', 'VIP'), ('vvip', 'VVIP')], max_length=20),
        ),
    ]
