# Generated by Django 6.0.3 on 2026-03-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_ticket_amount_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('early', 'Early Bird'), ('regular', 'Regular'), ('vip', 'VIP'), ('vvip', 'VVIP')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
