# Generated by Django 6.0.3 on 2026-04-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_tickettype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
